app:
  common:
    danmakuOutputDir: ~
  processor:
    # maybe these technical parameters can be moved to infra.
    bufferSize: 32768
    outputDir: ${INFRA_HTTP_OUTPUT_DIR}
    reserveMiddleFile: false
    portal-url-mappings:
      # iqiyi
      "www.iqiyi.com": iqiyi
      "iqiyi.com": iqiyi
      "cmts.iqiyi.com": iqiyi
      # bilibili
      "www.bilibili.com": bilibili
      "www.bilibili.tv": bilibili
      "bilibili.com": bilibili
      "bilibili.us": bilibili
      "bilibili.tv": bilibili
      # tencent video
      "v.qq.com": tencent-video
  generator:
    id-generator:
      strategy: uuid
  pipeline:
    items:
      bilibili:
        pipe-list: ~
        input-context-params:
        output-context-params:
      # This "convert-tencent-to-bilibili-danmaku" is pipeline name instead of pipe name
      # Don't be confused.
      convert-tencent-to-bilibili-danmaku:
        pipe-list:
        - convert-tencent-to-bilibili-danmaku
        input-context-params:
        - TENCENT_DANMAKU_FILE_PATH
        output-context-params:
        - BILIBILI_DANMAKU_FILE_PATH
infra:
  http:
    strategy: JDK
    bufferSize: 32768
    outputDir: ${INFRA_HTTP_OUTPUT_DIR}
    headers:
      default:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
        Accept-Encoding: "gzip, deflate, br"
        Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
#        Cache-Control: "no-cache"
        Pragma: no-cache
        Upgrade-Insecure-Requests: 1
      "www.bilibili.com":
        Sec-Ch-Ua-Mobile: ?0
        Sec-Ch-Ua-Platform: "Windows"
        Sec-Ch-Ua: -|
          "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
        Sec-Fetch-Dest: empty
        Sec-Fetch-Mode: cors
        Sec-Fetch-Site: same-site
    mime-extension-mappings:
      # json
      "application/json": .json
      "text/json": .json
      "text/html": .html
      # xml
      "application/xml": .xml
      "text/xml": .xml
  file:
    ass:
      script-info:
        scriptType: v4.00+
        collisions: Normal
        playResX: 560
        playResY: 420
        timer: 10.0000
      v4-plus-styles:
        format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
        style:
        - Fix,Microsoft YaHei UI,25,&H66FFFFFF,&H66FFFFFF,&H66000000,&H66000000,1,0,0,0,100,100,0,0,1,2,0,2,20,20,2,0
        - R2L,Microsoft YaHei UI,25,&H66FFFFFF,&H66FFFFFF,&H66000000,&H66000000,1,0,0,0,100,100,0,0,1,2,0,2,20,20,2,0
      events:
        format-fields: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        format-fields-mapping:
          BilibiliDanmakuDTO:
