app:
  processor:
    portal-url-mappings:
      # iqiyi
      "www.iqiyi.com": iqiyi
      "iqiyi.com": iqiyi
      "cmts.iqiyi.com": iqiyi
      # iqiyi
      "www.bilibili.com": bilibili
      "bilibili.com": bilibili
      "bilibili.us": bilibili
      "bilibili.tv": bilibili
infra:
  http:
    strategy: JDK
    bufferSize: 32768
    outputDir: ${INFRA_HTTP_OUTPUT_DIR}
