// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/IqiyiDanmuku.proto

package per.itachi.java.tools.danmuku.infra.protobuf.iqiyi;

public interface BulletInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:per.itachi.java.tools.danmuku.BulletInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>optional string content = 2;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>optional string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>optional string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
