// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/IqiyiDanmuku.proto

package per.itachi.java.tools.danmuku.infra.protobuf.iqiyi;

/**
 * Protobuf type {@code per.itachi.java.tools.danmuku.Danmuku}
 */
public final class Danmuku extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:per.itachi.java.tools.danmuku.Danmuku)
    DanmukuOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Danmuku.newBuilder() to construct.
  private Danmuku(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Danmuku() {
    entry_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Danmuku();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Danmuku_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Danmuku_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku.class, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku.Builder.class);
  }

  public static final int ENTRY_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry> entry_;
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  @java.lang.Override
  public java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry> getEntryList() {
    return entry_;
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder> 
      getEntryOrBuilderList() {
    return entry_;
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  @java.lang.Override
  public int getEntryCount() {
    return entry_.size();
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  @java.lang.Override
  public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry getEntry(int index) {
    return entry_.get(index);
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  @java.lang.Override
  public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder getEntryOrBuilder(
      int index) {
    return entry_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entry_.size(); i++) {
      output.writeMessage(6, entry_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entry_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, entry_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku)) {
      return super.equals(obj);
    }
    per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku other = (per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku) obj;

    if (!getEntryList()
        .equals(other.getEntryList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntryCount() > 0) {
      hash = (37 * hash) + ENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getEntryList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code per.itachi.java.tools.danmuku.Danmuku}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:per.itachi.java.tools.danmuku.Danmuku)
      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.DanmukuOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Danmuku_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Danmuku_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku.class, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku.Builder.class);
    }

    // Construct using per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (entryBuilder_ == null) {
        entry_ = java.util.Collections.emptyList();
      } else {
        entry_ = null;
        entryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Danmuku_descriptor;
    }

    @java.lang.Override
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku getDefaultInstanceForType() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku.getDefaultInstance();
    }

    @java.lang.Override
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku build() {
      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku buildPartial() {
      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku result = new per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku result) {
      if (entryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entry_ = entry_;
      } else {
        result.entry_ = entryBuilder_.build();
      }
    }

    private void buildPartial0(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku) {
        return mergeFrom((per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku other) {
      if (other == per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku.getDefaultInstance()) return this;
      if (entryBuilder_ == null) {
        if (!other.entry_.isEmpty()) {
          if (entry_.isEmpty()) {
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntryIsMutable();
            entry_.addAll(other.entry_);
          }
          onChanged();
        }
      } else {
        if (!other.entry_.isEmpty()) {
          if (entryBuilder_.isEmpty()) {
            entryBuilder_.dispose();
            entryBuilder_ = null;
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntryFieldBuilder() : null;
          } else {
            entryBuilder_.addAllMessages(other.entry_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 50: {
              per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry m =
                  input.readMessage(
                      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.PARSER,
                      extensionRegistry);
              if (entryBuilder_ == null) {
                ensureEntryIsMutable();
                entry_.add(m);
              } else {
                entryBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry> entry_ =
      java.util.Collections.emptyList();
    private void ensureEntryIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entry_ = new java.util.ArrayList<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry>(entry_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder> entryBuilder_;

    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry> getEntryList() {
      if (entryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entry_);
      } else {
        return entryBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public int getEntryCount() {
      if (entryBuilder_ == null) {
        return entry_.size();
      } else {
        return entryBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry getEntry(int index) {
      if (entryBuilder_ == null) {
        return entry_.get(index);
      } else {
        return entryBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder setEntry(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.set(index, value);
        onChanged();
      } else {
        entryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder setEntry(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.set(index, builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder addEntry(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(value);
        onChanged();
      } else {
        entryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder addEntry(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(index, value);
        onChanged();
      } else {
        entryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder addEntry(
        per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.add(builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder addEntry(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.add(index, builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder addAllEntry(
        java.lang.Iterable<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry> values) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entry_);
        onChanged();
      } else {
        entryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder clearEntry() {
      if (entryBuilder_ == null) {
        entry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entryBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public Builder removeEntry(int index) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.remove(index);
        onChanged();
      } else {
        entryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder getEntryBuilder(
        int index) {
      return getEntryFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder getEntryOrBuilder(
        int index) {
      if (entryBuilder_ == null) {
        return entry_.get(index);  } else {
        return entryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public java.util.List<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder> 
         getEntryOrBuilderList() {
      if (entryBuilder_ != null) {
        return entryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entry_);
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder addEntryBuilder() {
      return getEntryFieldBuilder().addBuilder(
          per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.getDefaultInstance());
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder addEntryBuilder(
        int index) {
      return getEntryFieldBuilder().addBuilder(
          index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.getDefaultInstance());
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
     */
    public java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder> 
         getEntryBuilderList() {
      return getEntryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder> 
        getEntryFieldBuilder() {
      if (entryBuilder_ == null) {
        entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder>(
                entry_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entry_ = null;
      }
      return entryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:per.itachi.java.tools.danmuku.Danmuku)
  }

  // @@protoc_insertion_point(class_scope:per.itachi.java.tools.danmuku.Danmuku)
  private static final per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku();
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Danmuku>
      PARSER = new com.google.protobuf.AbstractParser<Danmuku>() {
    @java.lang.Override
    public Danmuku parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Danmuku> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Danmuku> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Danmuku getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

