// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/IqiyiDanmuku.proto

package per.itachi.java.tools.danmuku.infra.protobuf.iqiyi;

public interface DanmukuOrBuilder extends
    // @@protoc_insertion_point(interface_extends:per.itachi.java.tools.danmuku.Danmuku)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry> 
      getEntryList();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry getEntry(int index);
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  int getEntryCount();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  java.util.List<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.Entry entry = 6;</code>
   */
  per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder getEntryOrBuilder(
      int index);
}
