// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/IqiyiDanmuku.proto

package per.itachi.java.tools.danmuku.infra.protobuf.iqiyi;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:per.itachi.java.tools.danmuku.Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo> 
      getBulletInfoList();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo getBulletInfo(int index);
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  int getBulletInfoCount();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  java.util.List<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder> 
      getBulletInfoOrBuilderList();
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder getBulletInfoOrBuilder(
      int index);
}
