// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/IqiyiDanmuku.proto

package per.itachi.java.tools.danmuku.infra.protobuf.iqiyi;

/**
 * Protobuf type {@code per.itachi.java.tools.danmuku.Entry}
 */
public final class Entry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:per.itachi.java.tools.danmuku.Entry)
    EntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Entry.newBuilder() to construct.
  private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Entry() {
    bulletInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Entry();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Entry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Entry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.class, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder.class);
  }

  public static final int BULLETINFO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo> bulletInfo_;
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  @java.lang.Override
  public java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo> getBulletInfoList() {
    return bulletInfo_;
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder> 
      getBulletInfoOrBuilderList() {
    return bulletInfo_;
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  @java.lang.Override
  public int getBulletInfoCount() {
    return bulletInfo_.size();
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  @java.lang.Override
  public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo getBulletInfo(int index) {
    return bulletInfo_.get(index);
  }
  /**
   * <pre>
   * becomes awesomeField
   * </pre>
   *
   * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
   */
  @java.lang.Override
  public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder getBulletInfoOrBuilder(
      int index) {
    return bulletInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bulletInfo_.size(); i++) {
      output.writeMessage(2, bulletInfo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bulletInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, bulletInfo_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry)) {
      return super.equals(obj);
    }
    per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry other = (per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry) obj;

    if (!getBulletInfoList()
        .equals(other.getBulletInfoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBulletInfoCount() > 0) {
      hash = (37 * hash) + BULLETINFO_FIELD_NUMBER;
      hash = (53 * hash) + getBulletInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code per.itachi.java.tools.danmuku.Entry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:per.itachi.java.tools.danmuku.Entry)
      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.EntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.class, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.Builder.class);
    }

    // Construct using per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bulletInfoBuilder_ == null) {
        bulletInfo_ = java.util.Collections.emptyList();
      } else {
        bulletInfo_ = null;
        bulletInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.IqiyiDanmuku.internal_static_per_itachi_java_tools_danmuku_Entry_descriptor;
    }

    @java.lang.Override
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry getDefaultInstanceForType() {
      return per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.getDefaultInstance();
    }

    @java.lang.Override
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry build() {
      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry buildPartial() {
      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry result = new per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry result) {
      if (bulletInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bulletInfo_ = java.util.Collections.unmodifiableList(bulletInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bulletInfo_ = bulletInfo_;
      } else {
        result.bulletInfo_ = bulletInfoBuilder_.build();
      }
    }

    private void buildPartial0(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry) {
        return mergeFrom((per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry other) {
      if (other == per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry.getDefaultInstance()) return this;
      if (bulletInfoBuilder_ == null) {
        if (!other.bulletInfo_.isEmpty()) {
          if (bulletInfo_.isEmpty()) {
            bulletInfo_ = other.bulletInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBulletInfoIsMutable();
            bulletInfo_.addAll(other.bulletInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.bulletInfo_.isEmpty()) {
          if (bulletInfoBuilder_.isEmpty()) {
            bulletInfoBuilder_.dispose();
            bulletInfoBuilder_ = null;
            bulletInfo_ = other.bulletInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bulletInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBulletInfoFieldBuilder() : null;
          } else {
            bulletInfoBuilder_.addAllMessages(other.bulletInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo m =
                  input.readMessage(
                      per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.PARSER,
                      extensionRegistry);
              if (bulletInfoBuilder_ == null) {
                ensureBulletInfoIsMutable();
                bulletInfo_.add(m);
              } else {
                bulletInfoBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo> bulletInfo_ =
      java.util.Collections.emptyList();
    private void ensureBulletInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bulletInfo_ = new java.util.ArrayList<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo>(bulletInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder> bulletInfoBuilder_;

    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo> getBulletInfoList() {
      if (bulletInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bulletInfo_);
      } else {
        return bulletInfoBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public int getBulletInfoCount() {
      if (bulletInfoBuilder_ == null) {
        return bulletInfo_.size();
      } else {
        return bulletInfoBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo getBulletInfo(int index) {
      if (bulletInfoBuilder_ == null) {
        return bulletInfo_.get(index);
      } else {
        return bulletInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder setBulletInfo(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo value) {
      if (bulletInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBulletInfoIsMutable();
        bulletInfo_.set(index, value);
        onChanged();
      } else {
        bulletInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder setBulletInfo(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder builderForValue) {
      if (bulletInfoBuilder_ == null) {
        ensureBulletInfoIsMutable();
        bulletInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        bulletInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder addBulletInfo(per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo value) {
      if (bulletInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBulletInfoIsMutable();
        bulletInfo_.add(value);
        onChanged();
      } else {
        bulletInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder addBulletInfo(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo value) {
      if (bulletInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBulletInfoIsMutable();
        bulletInfo_.add(index, value);
        onChanged();
      } else {
        bulletInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder addBulletInfo(
        per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder builderForValue) {
      if (bulletInfoBuilder_ == null) {
        ensureBulletInfoIsMutable();
        bulletInfo_.add(builderForValue.build());
        onChanged();
      } else {
        bulletInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder addBulletInfo(
        int index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder builderForValue) {
      if (bulletInfoBuilder_ == null) {
        ensureBulletInfoIsMutable();
        bulletInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        bulletInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder addAllBulletInfo(
        java.lang.Iterable<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo> values) {
      if (bulletInfoBuilder_ == null) {
        ensureBulletInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bulletInfo_);
        onChanged();
      } else {
        bulletInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder clearBulletInfo() {
      if (bulletInfoBuilder_ == null) {
        bulletInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bulletInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public Builder removeBulletInfo(int index) {
      if (bulletInfoBuilder_ == null) {
        ensureBulletInfoIsMutable();
        bulletInfo_.remove(index);
        onChanged();
      } else {
        bulletInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder getBulletInfoBuilder(
        int index) {
      return getBulletInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder getBulletInfoOrBuilder(
        int index) {
      if (bulletInfoBuilder_ == null) {
        return bulletInfo_.get(index);  } else {
        return bulletInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public java.util.List<? extends per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder> 
         getBulletInfoOrBuilderList() {
      if (bulletInfoBuilder_ != null) {
        return bulletInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bulletInfo_);
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder addBulletInfoBuilder() {
      return getBulletInfoFieldBuilder().addBuilder(
          per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder addBulletInfoBuilder(
        int index) {
      return getBulletInfoFieldBuilder().addBuilder(
          index, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>repeated .per.itachi.java.tools.danmuku.BulletInfo bulletInfo = 2;</code>
     */
    public java.util.List<per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder> 
         getBulletInfoBuilderList() {
      return getBulletInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder> 
        getBulletInfoFieldBuilder() {
      if (bulletInfoBuilder_ == null) {
        bulletInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfo.Builder, per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.BulletInfoOrBuilder>(
                bulletInfo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bulletInfo_ = null;
      }
      return bulletInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:per.itachi.java.tools.danmuku.Entry)
  }

  // @@protoc_insertion_point(class_scope:per.itachi.java.tools.danmuku.Entry)
  private static final per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry();
  }

  public static per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Entry>
      PARSER = new com.google.protobuf.AbstractParser<Entry>() {
    @java.lang.Override
    public Entry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Entry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Entry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public per.itachi.java.tools.danmuku.infra.protobuf.iqiyi.Entry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

